import os
import json
import urllib.request
import urllib.parse
from config import settings

class RAGEngine:
    """
    RAG Response Generation Engine.
    Supports cloud LLM integration (Gemini / OpenAI API) with seamless 
    smart local fallback grounded in Knowledge Base articles.
    """
    
    def generate_response(self, ticket_subject: str, ticket_description: str, category_name: str, kb_title: str, kb_content: str) -> str:
        """
        Generates an authoritative, helpful response grounded in the retrieved Knowledge Base article.
        """
        # Try Gemini API if key is present
        if settings.GEMINI_API_KEY:
            try:
                gemini_resp = self._call_gemini_api(ticket_subject, ticket_description, category_name, kb_title, kb_content)
                if gemini_resp:
                    return gemini_resp
            except Exception as e:
                print(f"[RAG Engine] Gemini API call error: {e}. Falling back to local RAG generator.")

        # Try OpenAI API if key is present
        if settings.OPENAI_API_KEY:
            try:
                openai_resp = self._call_openai_api(ticket_subject, ticket_description, category_name, kb_title, kb_content)
                if openai_resp:
                    return openai_resp
            except Exception as e:
                print(f"[RAG Engine] OpenAI API call error: {e}. Falling back to local RAG generator.")

        # Local Smart RAG Response Generator (Zero external API dependencies)
        return self._generate_local_rag_response(ticket_subject, ticket_description, category_name, kb_title, kb_content)

    def _generate_local_rag_response(self, ticket_subject: str, ticket_description: str, category_name: str, kb_title: str, kb_content: str) -> str:
        """
        Smart local RAG response generator that synthesizes the KB content cleanly.
        """
        clean_kb = kb_content.strip() if kb_content else "Please contact IT support for further assistance."
        
        # Extract main bullet points or steps from KB article
        kb_paragraphs = [p.strip() for p in clean_kb.split('\n') if p.strip()]
        kb_summary = "\n\n".join(kb_paragraphs)

        response = f"""Hello,

Thank you for reaching out to customer support regarding **"{ticket_subject}"**.

Based on your inquiry, here is the official resolution from our **{category_name}** knowledge base article (*"{kb_title}"*):

---
{kb_summary}
---

**Next Steps / Self-Service Instructions:**
1. Please follow the steps outlined above to resolve the issue.
2. If you are still experiencing difficulties, reply directly to this ticket and an agent will assist you immediately.

*Reference KB Article:* **{kb_title}**
*Auto-Generated by AI Support System*
"""
        return response.strip()

    def _call_gemini_api(self, ticket_subject: str, ticket_description: str, category_name: str, kb_title: str, kb_content: str) -> str:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={settings.GEMINI_API_KEY}"
        
        prompt = f"""You are an expert enterprise customer support AI assistant.
Answer the customer's support ticket strictly using the provided Knowledge Base article. 
Be professional, clear, concise, and helpful. Do not hallucinate outside of the provided context.

TICKET SUBJECT: {ticket_subject}
TICKET DETAILS: {ticket_description}
CATEGORY: {category_name}

KNOWLEDGE BASE ARTICLE:
Title: {kb_title}
Content:
{kb_content}

Generate a clear, polite support response:"""

        payload = {
            "contents": [{
                "parts": [{"text": prompt}]
            }]
        }
        
        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode('utf-8'),
            headers={'Content-Type': 'application/json'}
        )
        
        with urllib.request.urlopen(req, timeout=10) as response:
            res_data = json.loads(response.read().decode('utf-8'))
            text = res_data['candidates'][0]['content']['parts'][0]['text']
            return text.strip()

    def _call_openai_api(self, ticket_subject: str, ticket_description: str, category_name: str, kb_title: str, kb_content: str) -> str:
        url = "https://api.openai.com/v1/chat/completions"
        
        system_prompt = "You are an enterprise AI customer support assistant. Answer strictly based on the provided KB article."
        user_prompt = f"""TICKET SUBJECT: {ticket_subject}
TICKET DETAILS: {ticket_description}
CATEGORY: {category_name}

KB ARTICLE: {kb_title}
{kb_content}

Write a professional resolution email to the user."""

        payload = {
            "model": "gpt-4o-mini",
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "temperature": 0.2
        }
        
        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode('utf-8'),
            headers={
                'Content-Type': 'application/json',
                'Authorization': f'Bearer {settings.OPENAI_API_KEY}'
            }
        )
        
        with urllib.request.urlopen(req, timeout=10) as response:
            res_data = json.loads(response.read().decode('utf-8'))
            text = res_data['choices'][0]['message']['content']
            return text.strip()

rag_engine = RAGEngine()
